### ISSUE TITLE
Tools are placed incorrectly in layouts

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#479]
## Current Behavior

![image](https://user-images.githubusercontent.com/10647860/153973734-7ecd6d9d-64a4-4b7e-8f10-6cfa573d7781.png)

Possibly related to #471

**Comment by ZLLentz** [comment]
Checked a few versions, was not an issue in v2.0.0 but has been an issue for a while
I can conclude that nobody actually uses this feature, unfortunately (since no bug reports)

**Comment by klauer** [comment]
I just noticed this while looking at the log for a specific device. Something alarming (present in your screenshot as well) is the following:

```python
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/site-packages/typhos/suite.py", line 352, in show_subdisplay
    widget.load_best_template()
AttributeError: 'TyphosLogDisplay' object has no attribute 'load_best_template'
```

**Comment by ZLLentz** [comment]
I probably broke this when I introduced layout options in #450

**Comment by klauer** [comment]
> ```python
> Traceback (most recent call last):
>   File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/site-packages/typhos/suite.py", line 352, in show_subdisplay
>     widget.load_best_template()
> AttributeError: 'TyphosLogDisplay' object has no attribute 'load_best_template'
> ```

This exception traceback I pasted above will be resolved in #491.
I'm not sure if it will be sufficient for the closure of this issue, however.
